image: golang:1.13

stages:
  - build
  - test

unit_tests:
  stage: test
  script:
    - make test

int_tests:
  stage: test
  script:
    - make int_test

build:
  stage: build
  script:
    - make build

