apiVersion: ako.vmware.com/v1alpha1
kind: RouteBackendExtension
metadata:
  labels:
    app.kubernetes.io/name: ako-crd-operator
    app.kubernetes.io/managed-by: kustomize
  name: routebackendextension-sample
spec:
  # Load balancing configuration
  lbAlgorithm: LB_ALGORITHM_CONSISTENT_HASH
  lbAlgorithmConsistentHashHdr: X-Forwarded-For
  lbAlgorithmHash: LB_ALGORITHM_CONSISTENT_HASH_CUSTOM_HEADER
  
  # Session persistence configuration
  persistenceProfile: System-Persistence-Client-IP
  
  # Health monitoring configuration
  healthMonitor:
  - kind: "AVIREF"
    name: "healthmonitor-sample"
  
  # Backend TLS/SSL configuration
  backendTLS:
    
    # PKI Profile for certificate validation
    pkiProfile:
      kind: "CRD"
      name: "pkiprofile-sample"
    
    # Enable hostname verification during TLS handshake
    hostCheckEnabled: true
    
    # Domain names for backend certificate validation
    # Note: domainName can only be configured when hostCheckEnabled is set to true
    domainName:
    - "backend.example.com"
    - "api.example.com"