apiVersion: apps/v1
kind: Deployment
metadata:
  name: akc-deployment
  namespace: avi-system
  labels:
    app: akc-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akc-controller
  template:
    metadata:
      labels:
        app: akc-controller
    spec:
      containers:
      - name: akc-controller
        image: avi-k8s-controller:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CTRL_USERNAME
          valueFrom:
            secretKeyRef:
              name: avi-secret
              key: username
        - name: CTRL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: avi-secret
              key: password
        - name: CTRL_IPADDRESS
          valueFrom:
            configMapKeyRef:
              name: avi-k8s-config
              key: controllerIP
        - name: CTRL_VERSION
          valueFrom:
            configMapKeyRef:
              name: avi-k8s-config
              key: controllerVersion
        - name: CNI_PLUGIN
          valueFrom:
            configMapKeyRef:
              name: avi-k8s-config
              key: cniPlugin
        - name: SHARD_VS_SIZE
          valueFrom:
            configMapKeyRef:
              name: avi-k8s-config
              key: shardVSSize
        - name: FULL_SYNC_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: avi-k8s-config
              key: fullSyncFrequency
        - name: CLOUD_NAME
          valueFrom:
            configMapKeyRef:
              name: avi-k8s-config
              key: cloudName
        - name: CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: clusterName
        - name: DEFAULT_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: avi-k8s-config
              key: defaultDomain
        - name: DISABLE_STATIC_ROUTE_SYNC
          valueFrom:
            configMapKeyRef:
              name: avi-k8s-config
              key: disableStaticRouteSync
