apiVersion: v1
kind: Secret
metadata:
  name: avi-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.avicredentials.username }}
  password: {{ .Values.avicredentials.password }}