apiVersion: apps/v1
kind: Deployment
metadata:
  name: ako
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ako.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ako.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ako.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: ako-sa
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.persistentVolumeClaim }}
      volumes:
      - name: ako-pv-storage
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          {{ if .Values.persistentVolumeClaim }}
          volumeMounts:
          - mountPath: {{ .Values.mountPath }}
            name: ako-pv-storage
          {{ end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: CTRL_USERNAME
            valueFrom:
              secretKeyRef:
                name: avi-secret
                key: username
          - name: CTRL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: avi-secret
                key: password
          - name: CTRL_IPADDRESS
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: controllerIP
          - name: CTRL_VERSION
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: controllerVersion
          - name: CNI_PLUGIN
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: cniPlugin
          - name: SHARD_VS_SIZE
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: shardVSSize
          - name: SHARD_VS_PREFIX
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: shardVSPrefix
          - name: FULL_SYNC_INTERVAL
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: fullSyncFrequency
          - name: CLOUD_NAME
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: cloudName
          - name: VRF_CONTEXT
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: vrfRefName
          - name: DISABLE_STATIC_ROUTE_SYNC
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: disableStaticRouteSync
          - name: INGRESS_API
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: ingressApi
          - name: SYNC_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: syncNamespace
          - name: SUBNET_IP
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: subnetIP
          - name: SUBNET_CIDR
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: CIDR
          - name: NETWORK_NAME
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: NetworkName
          {{ if .Values.persistentVolumeClaim }}
          - name: USE_PVC
            value: "true"
          {{ end }}
          - name: LOG_FILE_NAME
            value: {{ printf "%s/%s" .Values.mountPath .Values.logFile }}
          - name: L7_SHARD_SCHEME
            valueFrom:
              configMapKeyRef:
                name: avi-k8s-config
                key: L7ShardingScheme
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
